name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK for Gradle
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Use Zulu OpenJDK
          java-version: '11'   # Recommended version for Android projects

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      # Step 4: Grant Gradle execution permission
      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      # Step 5: Build the project
      - name: Build with Gradle
        run: ./gradlew build

      # Step 6: Run unit tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Step 7: Assemble the APK
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug
